apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: weather-reprot.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Weather Report By City
  displayName: Weather Report
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - operator
  - weather
  links:
  - name: Weather Reprot
    url: https://weather-reprot.domain
  maintainers:
  - email: aneeshputtur@gmail.com
    name: aneesh
  maturity: alpha
  provider:
    name: aputtur
  version: 0.0.1
