# permissions for end users to view cityweathers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cityweather-viewer-role
rules:
- apiGroups:
  - weather.aputtur.com
  resources:
  - cityweathers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - weather.aputtur.com
  resources:
  - cityweathers/status
  verbs:
  - get
